name: Build container image and push to registry

on:
    push:
        branches:
            - "main"
        paths:
            - "src/**"
            - "Dockerfile"

jobs:
    build_and_push:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup docker
              uses: docker/setup-buildx-action@v2

            - name: Restore GCP service account key
              run: echo "$GCP_SERVICE_KEY" > gcp_service_key.json
              shell: bash
              env:
                  GCP_SERVICE_KEY: ${{secrets.GCP_SERVICE_KEY}}

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build image
              run: docker build -t michaelbui99/nordnet-fetch:latest .

            - name: Push image to Docker Hub
              run: docker push  michaelbui99/nordnet-fetch:latest
